// Package protocol defines the wire types for JSON-RPC 2.0 and the subset of
// the Model Context Protocol (MCP) that Agent Sentinel needs to inspect.
package protocol

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// Version is the only JSON-RPC version we speak.
const Version = "2.0"

// Standard JSON-RPC 2.0 error codes.
const (
	CodeParseError     = -32700
	CodeInvalidRequest = -32600
	CodeMethodNotFound = -32601
	CodeInvalidParams  = -32602
	CodeInternalError  = -32603

	// CodeBlockedBySentinel is an application-defined code (the -32000..-32099
	// range is reserved for implementations) used when a policy rejects a call.
	CodeBlockedBySentinel = -32001
)

// Kind classifies a JSON-RPC message.
type Kind int

const (
	KindInvalid      Kind = iota
	KindRequest           // has method and id
	KindNotification      // has method, no id
	KindResponse          // has id and result
	KindError             // has id and error
)

func (k Kind) String() string {
	switch k {
	case KindRequest:
		return "request"
	case KindNotification:
		return "notification"
	case KindResponse:
		return "response"
	case KindError:
		return "error"
	default:
		return "invalid"
	}
}

// ID is a JSON-RPC request id. The spec allows a string, a number or null, so
// we keep the raw bytes: this preserves the exact value for correlation and
// never loses precision on large integers.
type ID struct {
	raw json.RawMessage
}

// IsZero reports whether the id is absent (notifications).
func (i ID) IsZero() bool { return len(i.raw) == 0 }

// String returns a stable, comparable representation usable as a map key.
func (i ID) String() string {
	if i.IsZero() {
		return ""
	}
	return string(i.raw)
}

func (i ID) MarshalJSON() ([]byte, error) {
	if i.IsZero() {
		return []byte("null"), nil
	}
	return i.raw, nil
}

func (i *ID) UnmarshalJSON(b []byte) error {
	i.raw = append(i.raw[:0], bytes.TrimSpace(b)...)
	return nil
}

// NewIntID / NewStringID build ids programmatically (e.g. for synthetic
// responses generated by the policy engine).
func NewIntID(n int64) ID { return ID{raw: json.RawMessage(fmt.Sprintf("%d", n))} }

func NewStringID(s string) ID {
	b, _ := json.Marshal(s)
	return ID{raw: b}
}

// Error is the JSON-RPC error object.
type Error struct {
	Code    int             `json:"code"`
	Message string          `json:"message"`
	Data    json.RawMessage `json:"data,omitempty"`
}

func (e *Error) Error() string {
	return fmt.Sprintf("jsonrpc error %d: %s", e.Code, e.Message)
}

// Message is a union of every JSON-RPC 2.0 message shape. Decoding into a
// single struct lets the proxy sniff frames without knowing in advance
// whether they are requests, responses or notifications.
type Message struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      *ID             `json:"id,omitempty"`
	Method  string          `json:"method,omitempty"`
	Params  json.RawMessage `json:"params,omitempty"`
	Result  json.RawMessage `json:"result,omitempty"`
	Error   *Error          `json:"error,omitempty"`
}

// Kind reports which JSON-RPC message shape this is.
func (m *Message) Kind() Kind {
	hasID := m.ID != nil && !m.ID.IsZero()
	switch {
	case m.Method != "" && hasID:
		return KindRequest
	case m.Method != "":
		return KindNotification
	case m.Error != nil && m.ID != nil:
		return KindError
	case m.Result != nil && m.ID != nil:
		return KindResponse
	default:
		return KindInvalid
	}
}

// IDString returns the id as a map key, or "" when absent.
func (m *Message) IDString() string {
	if m.ID == nil {
		return ""
	}
	return m.ID.String()
}

// Parse decodes one JSON-RPC frame. A leading/trailing whitespace is tolerated.
// It returns an error for anything that is not a JSON-RPC 2.0 object (this is
// how the proxy distinguishes protocol frames from free-form text).
func Parse(frame []byte) (*Message, error) {
	frame = bytes.TrimSpace(frame)
	if len(frame) == 0 || frame[0] != '{' {
		return nil, fmt.Errorf("not a JSON object")
	}
	var m Message
	if err := json.Unmarshal(frame, &m); err != nil {
		return nil, err
	}
	if m.JSONRPC != Version {
		return nil, fmt.Errorf("unsupported jsonrpc version %q", m.JSONRPC)
	}
	if m.Kind() == KindInvalid {
		return nil, fmt.Errorf("not a valid JSON-RPC message")
	}
	return &m, nil
}

// NewErrorResponse builds a JSON-RPC error reply for the given request id.
func NewErrorResponse(id ID, code int, message string) *Message {
	return &Message{
		JSONRPC: Version,
		ID:      &id,
		Error:   &Error{Code: code, Message: message},
	}
}

// Marshal encodes the message as a single line (no trailing newline).
func (m *Message) Marshal() ([]byte, error) { return json.Marshal(m) }
